// <auto-generated />
namespace MusicStore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class store_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(store_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201407240208598_store_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
